### ISSUE TITLE
后续是否有增加亚洲诚信的计划

### ISSUE THREAD

**Issue by trytrytogo** [xiangyuecn/ACME-HTML-Web-Browser-Client#3]
工具用起来比较顺手。  
后续有增加亚洲诚信的计划吗？

**Comment by xiangyuecn** [comment]
只要有ACME服务地址，就可以用这个工具申请证书，手动填写服务地址即可。不过对于亚洲诚信的证书申请，我还没有从他们官网找到对应的API，也许是他门并不打算开放。

只找到一个 freessl.cn 提供了一层代理，透过他们的ACME服务去申请亚洲诚信的证书，不过 freessl.cn 要求注册账号并且索要手机号。

---------

注：我当时编写这个工具的一个原因，就是见到了好几个免费证书在线申请的网站，都要求注册才能用，其中就有 freessl.cn，另外一个就是 www.sslforfree.com ；他们网站里面的 输入框+免费创建证书按钮 明摆着就是诈骗😂

--------

刚才研究了一下亚洲诚信，诚信度不够高，说他有点东西吧 还藏着掖着，本人很排斥这种厂家。

![](https://user-images.githubusercontent.com/13175029/204233495-c7fd9fc8-7c53-4da4-a84e-a3c59034c5a7.png)

![](https://user-images.githubusercontent.com/13175029/204233646-bcf79c52-e5d0-45b4-97af-b4aba7d3505c.png)

![](https://user-images.githubusercontent.com/13175029/204233690-90a2a267-eceb-49b3-976d-1aa1375603ea.png)

**Comment by xiangyuecn** [comment]
强迫症犯了，又找他们客服问了一下，留了一个邮箱，看看会不会发API文档，可能还能抢救一下😂

![](https://user-images.githubusercontent.com/13175029/204238706-0d8fae8e-67c2-4e6f-bf53-54a7eea69fbe.png)

**Comment by trytrytogo** [comment]
> 强迫症犯了，又找他们客服问了一下，留了一个邮箱，看看会不会发API文档，可能还能抢救一下😂
> 
> ![](https://user-images.githubusercontent.com/13175029/204238706-0d8fae8e-67c2-4e6f-bf53-54a7eea69fbe.png)
好的。
感觉这家反正没啥

**Comment by xiangyuecn** [comment]
吃瓜，吃瓜。按业务员的说法，freessl.cn 就是亚洲诚信自己做的网站，别人想调他们的接口估计很难，收费的。只能注册freessl.cn 来得到ACME服务地址再去申请证书（但绕来绕去，就没有必须要这样操作了）

![](https://user-images.githubusercontent.com/13175029/204424726-91261b60-e8ca-4dba-9e7a-9cfbaee661f0.png)

![](https://user-images.githubusercontent.com/13175029/204424736-b074880a-f11e-4b85-bdb5-87d84f351b78.png)

**Comment by trytrytogo** [comment]
> 吃瓜，吃瓜。按业务员的说法，freessl.cn 就是亚洲诚信自己做的网站，别人想调他们的接口估计很难，收费的。只能注册freessl.cn 来得到ACME服务地址再去申请证书（但绕来绕去，就没有必须要这样操作了）
> 
> ![](https://user-images.githubusercontent.com/13175029/204424726-91261b60-e8ca-4dba-9e7a-9cfbaee661f0.png)
> 
> ![](https://user-images.githubusercontent.com/13175029/204424736-b074880a-f11e-4b85-bdb5-87d84f351b78.png)

原来是马甲公司啊。  懂了。
