### ISSUE TITLE
在edge中控制台填入代码后无法运行

### ISSUE THREAD

**Issue by CR2025** [xiangyuecn/ACME-HTML-Web-Browser-Client#7]
打开对应ACME服务URL后，等加载完成显示出"newAccount""newAuthz"等等
F12打开控制台粘贴代码，首先是提示“粘贴受限”，按提示解除受限后粘贴代码完成，回车运行显示报错
This document requires 'TrustedHTML' assignment.  VM16:2973

(匿名) | @ | VM16:2973
(匿名) | @ | VM16:2977

Uncaught TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.  VM16:2973
    at <anonymous>:2973:26
    at <anonymous>:2977:4

(匿名) | @ | VM16:2973
(匿名) | @ | VM16:2977

Microsoft Edge版本 127.0.2651.74 (正式版本) (64 位)

**Comment by xiangyuecn** [comment]
尝试删掉打开的acme网址后面的路径只留域名，进入404页面，然后再执行代码

**Comment by CR2025** [comment]
在去除acme网址后面的路径，在404页面执行代码成功，但实际申请时依然发生错误：[403]Invalid CORS request
申请buypass证书

**Comment by xiangyuecn** [comment]
应该是不支持buypass，他们可能是付费的

试了一下，估计是他们服务器阻止了浏览器请求，浏览器控制台里面可以看到：
Request URL: https://api.buypass.com/acme/new-acct
Request Method: POST
Status Code: 403 Forbidden

Invalid CORS request

**Comment by xiangyuecn** [comment]
去掉Origin请求头，就能正常申请buypass证书，浏览器里面估计是没办法了
